version: '3'
services:

  app:
    restart: always
    build:
      context: .
      args:
        CI: ${CI}
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 35729:35729
      - 9009:9009
